// flow-typed signature: 2390e9f19a6b2082a94cb183369bb3f9
// flow-typed version: <<STUB>>/rmrf_v^2.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rmrf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rmrf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rmrf/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rmrf/index' {
  declare module.exports: $Exports<'rmrf'>;
}
declare module 'rmrf/index.js' {
  declare module.exports: $Exports<'rmrf'>;
}
declare module 'rmrf/test/index.js' {
  declare module.exports: $Exports<'rmrf/test/index'>;
}
